/**
 * Integral database seed (F-1) — a demo company that has been operating for
 * about 200 days: users of every role, drivers and a fleet in every state,
 * hundreds of trips, service history, documents, resolved alerts and a full
 * audit trail. Built so every screen (dashboard chart, reports, auditoría,
 * alertas) has something real to show from the first login.
 *
 * The history itself is generated by seed-history.ts, a pure module whose
 * business rules are checked by seed-history.test.ts without a database. This
 * file only writes that plan to MySQL.
 *
 * Dates are relative to "today": the demo is always fresh, whenever it runs.
 *
 * Re-running resets the demo: users/drivers/vehicles are upserted back to
 * their seed state (including the demo passwords, so the credentials in the
 * README always work), and the transactional demo data — trips, maintenances,
 * documents, ALL alerts and the WHOLE audit trail — is cleared and recreated.
 * Keeping audit rows that point at trips that no longer exist would be worse
 * than rebuilding it. This is a demo seed: do not run it on real data.
 */
import bcrypt from 'bcryptjs';
import { prisma } from '../src/database/prisma-client';
import type { Prisma } from '../src/generated/prisma/client';
import { encrypt } from '../src/shared/utils/crypto';
import { FIXED_TRIP_ORIGIN } from '../src/config/constants';
import { samplePdf } from './sample-pdf';
import {
  COMPANY_SETTINGS,
  DOCUMENTS,
  DRIVERS,
  DRIVER_PASSWORD,
  STAFF,
  VEHICLES,
  buildAuditRows,
  buildHistory,
  type ActorKey,
  type DocDef,
  type DocType,
  type IdMaps,
  type VehicleKey,
} from './seed-history';

const BCRYPT_ROUNDS = 10;
const BATCH = 200;

const DOC_TITLES: Record<DocType, string> = {
  DNI: 'Documento Nacional de Identidad',
  LICENSE: 'Licencia de conducir',
  ART: 'Constancia de ART',
  PSYCHOPHYSICAL: 'Certificado psicofísico',
};

/** A real, downloadable PDF for each sample document (files live in the DB). */
function sampleDocumentFile(doc: DocDef, expiry: Date): Uint8Array<ArrayBuffer> {
  const driver = DRIVERS.find((d) => d.key === doc.driver)!;
  return samplePdf(DOC_TITLES[doc.type], [
    `Titular: ${driver.name}`,
    `DNI: ${driver.dni}`,
    `Vencimiento: ${expiry.toLocaleDateString('es-AR', { timeZone: 'UTC' })}`,
    '',
    'Documento de muestra generado por el seed. Datos ficticios.',
  ]);
}

/** Runs creates in array transactions (fast, and ids come back in order). */
async function createInBatches<T>(items: T[], create: (item: T) => Prisma.PrismaPromise<{ id: number }>): Promise<number[]> {
  const ids: number[] = [];
  for (let i = 0; i < items.length; i += BATCH) {
    const created = await prisma.$transaction(items.slice(i, i + BATCH).map(create));
    ids.push(...created.map((c) => c.id));
  }
  return ids;
}

async function main(): Promise<void> {
  const h = buildHistory(new Date());
  const { clock } = h;

  // --- Catalog & company settings -------------------------------------------
  const minor = await prisma.maintenanceType.upsert({
    where: { name: 'Preventivo menor' },
    update: {},
    create: {
      name: 'Preventivo menor',
      description: 'Cambio de aceite, filtros y engrase',
      kmAlert: 10000,
      kmTarget: 20000,
      monthsAlert: 3,
      monthsTarget: 6,
    },
    select: { id: true },
  });
  const major = await prisma.maintenanceType.upsert({
    where: { name: 'Preventivo mayor' },
    update: {},
    create: {
      name: 'Preventivo mayor',
      description: 'Revisión de frenos, suspensión y alineación',
      kmAlert: 80000,
      kmTarget: 120000,
      monthsAlert: 12,
      monthsTarget: 12,
    },
    select: { id: true },
  });
  await prisma.companySettings.upsert({
    where: { id: 1 },
    update: COMPANY_SETTINGS,
    create: { id: 1, ...COMPANY_SETTINGS },
  });

  // --- Users & drivers (reset to their seed state) ---------------------------
  const users = {} as Record<ActorKey, number>;
  for (const s of STAFF) {
    const passwordHash = await bcrypt.hash(s.password, BCRYPT_ROUNDS);
    const data = {
      name: s.name,
      role: s.role,
      passwordHash,
      isActive: true,
      deletedAt: null,
      createdAt: clock.at(s.joinedDay, 10),
    };
    const u = await prisma.user.upsert({
      where: { email: s.email },
      update: data,
      create: { email: s.email, ...data },
      select: { id: true },
    });
    users[s.key] = u.id;
  }

  const driverHash = await bcrypt.hash(DRIVER_PASSWORD, BCRYPT_ROUNDS);
  for (const d of DRIVERS) {
    const userData = {
      name: d.name,
      role: 'DRIVER' as const,
      passwordHash: driverHash,
      isActive: d.active,
      deletedAt: null,
      createdAt: clock.at(d.joinedDay, 10.5),
    };
    const u = await prisma.user.upsert({
      where: { email: d.email },
      update: userData,
      create: { email: d.email, ...userData },
      select: { id: true },
    });
    users[d.key] = u.id;

    const stats = h.driverStats[d.key];
    const driverData = {
      dni: d.dni,
      licenseCategory: d.licenseCategory,
      licenseExpiryDate: clock.dateOnly(d.licenseDays),
      encryptedPassword: encrypt(DRIVER_PASSWORD),
      completedTrips: stats.completedTrips,
      avgKm: stats.avgKm,
    };
    await prisma.driver.upsert({
      where: { userId: u.id },
      update: driverData,
      create: { userId: u.id, ...driverData },
    });
  }

  // --- Fleet (reset to its final state) --------------------------------------
  const vehicles = {} as Record<VehicleKey, number>;
  for (const v of VEHICLES) {
    const final = h.vehicleFinal[v.plate];
    const data = {
      model: v.model,
      year: v.year,
      initialKm: v.startKm,
      accumulatedKm: final.km,
      lastMaintenanceDate: final.lastMaintenanceDate,
      insuranceExpiryDate: clock.dateOnly(v.insuranceDays),
      status: v.finalStatus,
      deletedAt: null,
      createdAt: clock.at(v.joinedDay, 11),
    };
    const row = await prisma.vehicle.upsert({
      where: { licensePlate: v.plate },
      update: data,
      create: { licensePlate: v.plate, ...data },
      select: { id: true },
    });
    vehicles[v.plate] = row.id;
  }

  // --- Clear the transactional demo data --------------------------------------
  const driverIds = DRIVERS.map((d) => users[d.key]);
  const staffIds = STAFF.map((s) => users[s.key]);
  const vehicleIds = Object.values(vehicles);
  await prisma.auditLog.deleteMany({});
  await prisma.alert.deleteMany({});
  await prisma.trip.deleteMany({
    where: {
      OR: [
        { driverId: { in: driverIds } },
        { operatorId: { in: staffIds } },
        { vehicleId: { in: vehicleIds } },
      ],
    },
  });
  await prisma.maintenance.deleteMany({ where: { vehicleId: { in: vehicleIds } } });
  await prisma.driverDocument.deleteMany({ where: { driverId: { in: driverIds } } });

  // --- Documents ----------------------------------------------------------------
  const documents: Record<string, number> = {};
  const docIds = await createInBatches(DOCUMENTS, (doc) => {
    const expiryDate = clock.dateOnly(doc.expiryDays);
    const content = sampleDocumentFile(doc, expiryDate);
    return prisma.driverDocument.create({
      data: {
        driverId: users[doc.driver],
        documentType: doc.type,
        expiryDate,
        fileName: `${doc.key}.pdf`,
        mimeType: 'application/pdf',
        fileSize: content.byteLength,
        content,
        uploadedAt: clock.at(doc.uploadedDay, doc.deletedDay === undefined ? 10.5 : 10),
        deletedAt: doc.deletedDay === undefined ? null : clock.at(doc.deletedDay, 10),
      },
      select: { id: true },
    });
  });
  DOCUMENTS.forEach((doc, i) => (documents[doc.key] = docIds[i]!));

  // --- Trips (in creation order, so ids grow with time) -----------------------
  const tripIds = await createInBatches(h.trips, (t) =>
    prisma.trip.create({
      data: {
        origin: FIXED_TRIP_ORIGIN,
        destination: t.destination,
        departureAt: t.departureAt,
        status: t.status,
        estimatedDistanceKm: t.estimatedDistanceKm,
        estimatedTimeMin: t.estimatedTimeMin,
        notes: t.notes,
        operatorId: users[t.createdBy],
        driverId: t.driver ? users[t.driver] : null,
        vehicleId: t.vehicle ? vehicles[t.vehicle] : null,
        departureKm: t.departureKm,
        arrivalKm: t.arrivalKm,
        assignedAt: t.assignedAt,
        finishedAt: t.finishedAt,
        finishedById: t.finishedBy ? users[t.finishedBy] : null,
        createdAt: t.createdAt,
      },
      select: { id: true },
    }),
  );

  // --- Maintenances -------------------------------------------------------------
  const maintenanceTypes = { minor: minor.id, major: major.id };
  const maintenanceIds = await createInBatches(h.maintenances, (m) =>
    prisma.maintenance.create({
      data: {
        vehicleId: vehicles[m.vehicle],
        maintenanceTypeId: maintenanceTypes[m.type],
        status: m.status,
        scheduledAt: m.scheduledAt,
        completedAt: m.completedAt,
        km: m.km,
        notes: m.notes,
        nextMaintenanceKm: m.nextMaintenanceKm,
        createdAt: m.createdAt,
      },
      select: { id: true },
    }),
  );

  // --- Resolved alerts (pending ones are raised by the evaluator job) ----------
  const alertIds = await createInBatches(h.alerts, (a) => {
    const entity =
      a.entity.kind === 'vehicle'
        ? { entityType: 'VEHICLE', entityId: vehicles[a.entity.key] }
        : a.entity.kind === 'driver'
          ? { entityType: 'DRIVER', entityId: users[a.entity.key] }
          : { entityType: 'DRIVER_DOCUMENT', entityId: documents[a.entity.key]! };
    return prisma.alert.create({
      data: {
        alertType: a.alertType,
        description: a.description,
        ...entity,
        raisedAt: a.raisedAt,
        status: 'RESOLVED',
        resolvedById: users.admin,
        resolvedAt: a.resolvedAt,
      },
      select: { id: true },
    });
  });

  // --- Audit trail ----------------------------------------------------------------
  const ids: IdMaps = {
    users,
    vehicles,
    trips: tripIds,
    maintenances: maintenanceIds,
    documents,
    alerts: alertIds,
    maintenanceTypes,
  };
  const auditRows = buildAuditRows(h, ids);
  for (let i = 0; i < auditRows.length; i += 500) {
    await prisma.auditLog.createMany({
      data: auditRows.slice(i, i + 500).map((r) => ({
        userId: r.userId,
        action: r.action,
        entity: r.entity,
        entityId: r.entityId,
        occurredAt: r.occurredAt,
        ...(r.previousData ? { previousData: r.previousData as Prisma.InputJsonValue } : {}),
        ...(r.newData ? { newData: r.newData as Prisma.InputJsonValue } : {}),
      })),
    });
  }

  const count = (status: string) => h.trips.filter((t) => t.status === status).length;
  // eslint-disable-next-line no-console
  console.log(
    [
      'Seed completed:',
      `  ${STAFF.length} staff users, ${DRIVERS.length} drivers (1 dismissed), ${VEHICLES.length} vehicles`,
      `  ${h.trips.length} trips (${count('COMPLETED')} completed, ${count('CANCELLED')} cancelled, ` +
        `${count('IN_PROGRESS')} in progress, ${count('PENDING_ASSIGNMENT')} pending)`,
      `  ${h.maintenances.length} maintenances, ${DOCUMENTS.length} documents, ` +
        `${h.alerts.length} resolved alerts, ${auditRows.length} audit entries`,
      '  Pending alerts are raised by the evaluator job ~15 s after the API starts',
      '  (or right away with POST /api/v1/alerts/evaluate).',
    ].join('\n'),
  );
}

main()
  .catch((err) => {
    // eslint-disable-next-line no-console
    console.error(err);
    process.exit(1);
  })
  .finally(() => void prisma.$disconnect());
