-- Cancelacion de viajes y mantenimientos: nuevo estado CANCELLED.
ALTER TABLE `trips` MODIFY `status` ENUM('PENDING_ASSIGNMENT', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED') NOT NULL DEFAULT 'PENDING_ASSIGNMENT';
ALTER TABLE `maintenances` MODIFY `status` ENUM('PENDING', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED') NOT NULL DEFAULT 'PENDING';
